//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SftpConnectorMicroservice {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SftpConnectorMicroservice.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize SFTP connection. Ensure that the specified server&apos;s configuration details are correct..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Details provided are not valid. Error: {0}.
        /// </summary>
        internal static string InvalidAuthenticationDetails {
            get {
                return ResourceManager.GetString("InvalidAuthenticationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is not base64 encoded..
        /// </summary>
        internal static string InvalidBase64String {
            get {
                return ResourceManager.GetString("InvalidBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Upload File Operation is invalid if appendIfExist is true and temporary folder is used..
        /// </summary>
        internal static string InvalidOperationWithTemporaryFolder {
            get {
                return ResourceManager.GetString("InvalidOperationWithTemporaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null, empty, or cannot contain only white-space characters..
        /// </summary>
        internal static string IsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("IsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Details are not found..
        /// </summary>
        internal static string NoAuthenticationDetailsFound {
            get {
                return ResourceManager.GetString("NoAuthenticationDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is temporarily unavailable. Please retry..
        /// </summary>
        internal static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Server Host Key cannot be null or empty if Accept Any SSHServerHostKey value is false.
        /// </summary>
        internal static string SftpAdapter_AcceptAnySSHServerHostKeyNull {
            get {
                return ResourceManager.GetString("SftpAdapter_AcceptAnySSHServerHostKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appending data to the file &apos;{0}&apos; failed as the file size is more than 2147483647  bytes..
        /// </summary>
        internal static string SftpAdapter_AppendFailure {
            get {
                return ResourceManager.GetString("SftpAdapter_AppendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get File Error. Ensure that the file exists on specified SFTP server..
        /// </summary>
        internal static string SftpAdapter_GetFileError {
            get {
                return ResourceManager.GetString("SftpAdapter_GetFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileInclude and FileExclude Mask are not valid..
        /// </summary>
        internal static string SftpAdapter_InvalidRegexExpression {
            get {
                return ResourceManager.GetString("SftpAdapter_InvalidRegexExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} does not exist on SFTP Server..
        /// </summary>
        internal static string SftpAdapter_NotFound {
            get {
                return ResourceManager.GetString("SftpAdapter_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP Connector Port number is out of range..
        /// </summary>
        internal static string SftpAdapter_OutOfRangePort {
            get {
                return ResourceManager.GetString("SftpAdapter_OutOfRangePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key is mandatory if private key password is not null or empty.
        /// </summary>
        internal static string SftpAdapter_PrivateKeyPasswordNull {
            get {
                return ResourceManager.GetString("SftpAdapter_PrivateKeyPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}. Sftp Error Code: &apos;{1}&apos;. Sftp Error message: &apos;{2}&apos;..
        /// </summary>
        internal static string SftpAdapter_SftpErrorMessage {
            get {
                return ResourceManager.GetString("SftpAdapter_SftpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that the specified Temporary folder path: {0} exists on the SFTP server..
        /// </summary>
        internal static string SftpAdapter_TemporaryFolderNotExist {
            get {
                return ResourceManager.GetString("SftpAdapter_TemporaryFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred during connection establishment to the specified SFTP server..
        /// </summary>
        internal static string SftpAdapter_TimeoutInGetConnection {
            get {
                return ResourceManager.GetString("SftpAdapter_TimeoutInGetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Delete File operation.
        /// </summary>
        internal static string SuccessfulDelete {
            get {
                return ResourceManager.GetString("SuccessfulDelete", resourceCulture);
            }
        }
    }
}
